---
- name: find the result
  hosts: 192.168.2.30
  become: yes
  gather_facts: no
 
  vars:
    ansible_become_password: "vagarant"

  tasks:
    - name: register and find result
      #shell: "find /etc -name passwd"
      shell: "find psswd*" 
      #args:
      #  chdir: "/etc"
      register: find_results
      ignore_errors: yes

    - name: display find_results
      debug:
        var: find_results
      when: find_results.rc == 1
   
