---
- name: uninstall httpd service
  hosts: web
  become: yes

  vars:
    ansible_become_pass: "vagrant"

  tasks:
    - name: stop httpd
      ansible.builtin.service:
        name: httpd
        state: stopped

    - name: remove index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: stopped httpd
      ansible.builtin.service:
        name: httpd
        state: stopped

...
